### ISSUE TITLE
Minified builds don't keep license headers

### ISSUE THREAD

**Issue by XhmikosR** [Johann-S/bs-customizer#12]

**Comment by Johann-S** [comment]
that's because they don't respect the comment regex on our UglifyJS config https://github.com/Johann-S/bs-customizer/blob/master/src/file-util.js#L3

**Comment by XhmikosR** [comment]
True, forgot about it :) We should add them there.

**Comment by XhmikosR** [comment]
I'm gonna reopen this so that we don't forget to add the license header upstream.

**Comment by XhmikosR** [comment]
https://github.com/twbs/bootstrap/issues/27301
