### ISSUE TITLE
Sass doesn't build anymore

### ISSUE THREAD

**Issue by MartijnCuppens** [Johann-S/bs-customizer#26]
Looks like something went wrong in one of the latest builds. Error triggers when css is generated, no problems with the js files.
  
![image](https://user-images.githubusercontent.com/11559216/46171495-fd98b700-c2a0-11e8-9d64-1c90e7941cd6.png)

**Comment by Johann-S** [comment]
I don't understand 😟 
`sass.worker.js` is in our `dist` folder so it should work fine 🤔

**Comment by Johann-S** [comment]
Oh ok I found !

**Comment by Johann-S** [comment]
BTW thank you @MartijnCuppens 👍

**Comment by MartijnCuppens** [comment]
No problem 😉
