### ISSUE TITLE
Doesn't work on Firefox

### ISSUE THREAD

**Issue by XhmikosR** [Johann-S/bs-customizer#3]
Tested using Firefox 62.0.2.

**Comment by Johann-S** [comment]
Closed thanks to: https://github.com/Johann-S/bs-customizer/commit/bfbfabd285a3b0ca13cb3a8887b46a7b3ae2afd7

**Comment by XhmikosR** [comment]
Thanks! But now it's a .txt file. Also the new dialog could use some styling :)
