### ISSUE TITLE
Split JavaScript

### ISSUE THREAD

**Issue by XhmikosR** [Johann-S/bs-customizer#30]
No need to keep this as a one huge file. As long as everything is loaded asynchronously we can just move some stuff outside of the main bundle.

**Comment by Johann-S** [comment]
Sure ! 

I would like to move minifier in an other entry 🤔

**Comment by XhmikosR** [comment]
Yeah, definitely. Also, clean-css and any other stuff that aren't needed for initial page load should be moved outside of the main bundle too...

**Comment by Johann-S** [comment]
Yep I included clean-css when I said minifier 👍
