### ISSUE TITLE
Add js prefix to all elements where javascript is applied to.

### ISSUE THREAD

**Issue by MartijnCuppens** [Johann-S/bs-customizer#40]
In my own projects I always add a `js-` prefix to classes of element where javascript is applied to.
By using `js-` prefix for classes in DOM elements you decouple functional aspects of these elements from CSS ones. An example:

```html
<a class="btn js-popup">Click me!</a>
```

This has some advantages:
- as css coder, you can easily change anchor design by changing btn class and not worry it'll break pop up behavior.
- and conversely, as JavaScript developer you can remove popup behavior and never break any existing CSS rules.

(source: https://coderwall.com/p/qktuzw/decouple-javascript-classes-from-css-ones-by-using-prefix, this just perfectly described what I meant)

What do you think @Johann-S, @XhmikosR?

**Comment by XhmikosR** [comment]
While this might be a good idea for advanced usages, the classes here
should be exactly what they are upstream, at least by default.

**Comment by MartijnCuppens** [comment]
> the classes here should be exactly what they are upstream, at least by default.
Can you clarify this a bit more?

**Comment by Johann-S** [comment]
It seems a good idea to me 👍

**Comment by XhmikosR** [comment]
Wait, you mean add the ability to specify an optional prefix?

Or you meant this for the customizer's own code?

**Comment by MartijnCuppens** [comment]
@XhmikosR, the customizer's code, didn't realise this wasn't clear untill I read your comment 😀

**Comment by XhmikosR** [comment]
Ah, OK then :)

**Comment by MartijnCuppens** [comment]
Haha, the *good first issue* tag, thanks @Johann-S!
I'll have a look at this 🙂
