### ISSUE TITLE
Verify builds are OK

### ISSUE THREAD

**Issue by XhmikosR** [Johann-S/bs-customizer#84]
Quickly comparing 4.1.3, I notice quite a big difference in the CSS at least.

We need to verify that's OK, and understand why it happens.

**Comment by Johann-S** [comment]
https://github.com/Johann-S/bs-customizer/commit/af69dee14c127076e30f2e63ec7042a275ba5789 partially fix that, because there was a lack of `_grid.scss` due to a typo error

**Comment by Johann-S** [comment]
Closed thanks to https://github.com/Johann-S/bs-customizer/pull/85
