### ISSUE TITLE
Update to Bootstrap v4.3.1

### ISSUE THREAD

**Issue by Johann-S** [Johann-S/bs-customizer#91]
We need to update to the latest release

@MartijnCuppens do you know if there is new SCSS files ? 

I'll handle the JS part

**Comment by MartijnCuppens** [comment]
There are no new components, so no changes to `scss/bootstrap.scss`. The only file that was added in `v4.3` was `scss/vendor/rfs.scss` I guess, but if we just include the `scss/mixin.scss` file, this wouldn't matter.

**Comment by Johann-S** [comment]
because rfs is added in Mixin ?

**Comment by mobihack** [comment]
`scss/vendor/rfs.scss` is added in `scss/mixins.scss`.

> https://unpkg.com/bootstrap@4.3.1/scss/_mixins.scss

**Comment by Johann-S** [comment]
Indeed thanks @mobihack 👍

**Comment by mobihack** [comment]
You're welcome. I am currently working on a pull request right now. Do accept it.
